# Generated by Django 5.2.3 on 2025-06-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(choices=[('BRL', 'R$'), ('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='BRL', max_length=3)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True)),
                ('status', models.CharField(choices=[('DRA', 'Draft'), ('PUB', 'Published'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='DRA', max_length=3)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this event on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category')),
                ('tags', models.ManyToManyField(blank=True, to='events.tag')),
            ],
            options={
                'ordering': ['-created_at', 'start_time'],
            },
        ),
    ]
