# Generated by Django 5.2.3 on 2025-07-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_featured_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_text',
            field=models.CharField(blank=True, help_text="Custom text to display on the featured badge ('Hot!', 'New!', 'Limited Spots!'). Only visible if Is featured is checked.", max_length=20, null=True),
        ),
    ]
