# Generated by Django 5.2.3 on 2025-07-02 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Leave empty for unlimited.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
